"""
Structured interview question bank used by the AI Interview Coach.

The data is intentionally separated from the runtime logic so the question
system can scale without turning `knowledge_base.py` into a wall of literals.
"""

from __future__ import annotations

from typing import Dict, List, Optional


def entry(
    question: str,
    keywords: List[str],
    concepts: List[str],
    key_points: List[str],
    example: str = "",
    role_tags: Optional[List[str]] = None,
    skill_tags: Optional[List[str]] = None,
) -> Dict:
    return {
        "question": question,
        "keywords": keywords,
        "concepts": concepts,
        "ideal_answer": {
            "key_points": key_points,
            "example": example,
        },
        "role_tags": role_tags or [],
        "skill_tags": skill_tags or [],
    }


QUESTION_BLUEPRINT: Dict[str, Dict[str, List[Dict]]] = {
    "python": {
        "beginner": [
            entry(
                "What is the difference between a list and a tuple in Python, and when would you choose one over the other?",
                ["list", "tuple", "mutable", "immutable", "ordered"],
                ["data structures", "mutability", "tradeoffs"],
                ["Lists are mutable", "Tuples are immutable", "Choice depends on update needs and intent"],
                "items = [1, 2, 3]\ncoords = (18.5, 73.8)",
                role_tags=["software engineer", "backend developer", "data scientist"],
                skill_tags=["python"],
            ),
            entry(
                "Explain how Python handles variable scope inside functions and what the LEGB rule means.",
                ["scope", "local", "enclosing", "global", "built-in"],
                ["name resolution", "function scope", "LEGB"],
                ["LEGB defines lookup order", "Local variables shadow outer names", "global/nonlocal can change lookup behavior"],
                "count = 0\ndef outer():\n    value = 'x'\n    def inner():\n        return value",
                role_tags=["software engineer", "backend developer"],
                skill_tags=["python"],
            ),
            entry(
                "How would you explain list comprehensions to a beginner, and why are they useful?",
                ["list comprehension", "loop", "filter", "expression", "readable"],
                ["iteration", "transformation", "Pythonic style"],
                ["List comprehensions build lists from expressions", "They can include conditions", "They reduce boilerplate for simple transforms"],
                "squares = [x * x for x in range(5) if x % 2 == 0]",
                role_tags=["software engineer", "data scientist"],
                skill_tags=["python"],
            ),
        ],
        "intermediate": [
            entry(
                "What problem do decorators solve in Python, and can you walk through a realistic use case?",
                ["decorator", "wrapper", "@", "function", "reuse"],
                ["higher-order functions", "cross-cutting concerns", "abstraction"],
                ["Decorators wrap behavior around functions", "They help reuse logging/auth/timing logic", "They preserve a clean core function"],
                "@timer\ndef fetch_users():\n    return repo.all()",
                role_tags=["software engineer", "backend developer"],
                skill_tags=["python", "flask", "django"],
            ),
            entry(
                "Compare generators with normal functions that return full collections. When are generators the better choice?",
                ["generator", "yield", "memory", "lazy", "iterator"],
                ["lazy evaluation", "stream processing", "memory efficiency"],
                ["Generators yield values on demand", "They reduce memory use for large sequences", "They are useful for pipelines and streaming"],
                "def read_lines(path):\n    with open(path) as f:\n        for line in f:\n            yield line.strip()",
                role_tags=["software engineer", "data scientist", "backend developer"],
                skill_tags=["python"],
            ),
            entry(
                "Suppose a Python service becomes slow under load. Which language-level issues would you inspect first before blaming infrastructure?",
                ["profiling", "loops", "I/O", "caching", "GIL"],
                ["performance debugging", "bottleneck analysis", "runtime behavior"],
                ["Profile before optimizing", "Check repeated work and blocking I/O", "Separate CPU-bound from I/O-bound issues"],
                "Use cProfile, inspect repeated DB/API calls, and cache expensive pure computations.",
                role_tags=["backend developer", "software engineer"],
                skill_tags=["python", "backend"],
            ),
        ],
        "advanced": [
            entry(
                "How does Python's GIL affect concurrency, and how would your design change for CPU-bound versus I/O-bound workloads?",
                ["GIL", "threading", "multiprocessing", "I/O-bound", "CPU-bound"],
                ["runtime internals", "concurrency strategy", "system design"],
                ["GIL limits parallel bytecode execution in threads", "Threads still work well for I/O-bound tasks", "CPU-heavy work often needs multiprocessing or native extensions"],
                "Use asyncio or threads for HTTP calls; use multiprocessing for image processing.",
                role_tags=["backend developer", "software engineer"],
                skill_tags=["python", "backend"],
            ),
            entry(
                "What are context managers in Python, and how would you create a custom one for a non-file resource?",
                ["context manager", "__enter__", "__exit__", "with", "cleanup"],
                ["resource management", "protocols", "exception safety"],
                ["Context managers guarantee setup and cleanup", "They improve safety around resources", "Custom ones can manage locks, timers, or connections"],
                "class Timer:\n    def __enter__(self): ...\n    def __exit__(self, exc_type, exc, tb): ...",
                role_tags=["backend developer", "software engineer"],
                skill_tags=["python"],
            ),
            entry(
                "Describe a situation where metaclasses are justified in Python and when they are overengineering.",
                ["metaclass", "class creation", "framework", "magic", "complexity"],
                ["advanced Python", "abstraction boundaries", "maintainability"],
                ["Metaclasses customize class creation", "They are rare and mostly useful in frameworks", "Readability and maintenance costs are the main tradeoff"],
                "A framework may register subclasses automatically during class creation.",
                role_tags=["software engineer"],
                skill_tags=["python"],
            ),
        ],
    },
    "java": {
        "beginner": [
            entry(
                "What does the JVM do, and why does it allow Java applications to be platform independent?",
                ["JVM", "bytecode", "platform independent", "compile", "runtime"],
                ["execution model", "bytecode", "portability"],
                ["Java source compiles to bytecode", "JVM executes bytecode on each platform", "This separation enables portability"],
                "javac App.java\njava App",
                role_tags=["software engineer", "backend developer"],
                skill_tags=["java"],
            ),
            entry(
                "Explain the four core OOP principles in Java with simple examples.",
                ["encapsulation", "inheritance", "polymorphism", "abstraction", "class"],
                ["oop fundamentals", "object design", "modularity"],
                ["Define the four principles", "Give small examples", "Explain why they improve maintainability"],
                "A Payment class can expose pay() while hiding internal validation details.",
                role_tags=["software engineer", "backend developer"],
                skill_tags=["java", "oop"],
            ),
            entry(
                "What is the difference between checked and unchecked exceptions in Java, and how should teams use them wisely?",
                ["checked", "unchecked", "exception", "runtime", "compile-time"],
                ["error handling", "API design", "contracts"],
                ["Checked exceptions are enforced by the compiler", "Unchecked exceptions represent programming/runtime issues", "Use them consistently to communicate contracts"],
                "IOException is checked; NullPointerException is unchecked.",
                role_tags=["software engineer", "backend developer"],
                skill_tags=["java"],
            ),
        ],
        "intermediate": [
            entry(
                "How does the Java Collections Framework help with performance and clean design decisions?",
                ["collections", "List", "Set", "Map", "interface"],
                ["data structures", "abstraction", "performance tradeoffs"],
                ["Interfaces decouple code from implementations", "Different collections optimize different operations", "Choosing the right one improves clarity and performance"],
                "Use HashMap for lookups, ArrayList for indexed traversal, LinkedHashSet when order matters.",
                role_tags=["software engineer", "backend developer"],
                skill_tags=["java", "dsa"],
            ),
            entry(
                "When would you use an interface, an abstract class, or a concrete utility class in Java?",
                ["interface", "abstract class", "implementation", "contract", "inheritance"],
                ["API design", "inheritance strategy", "flexibility"],
                ["Interfaces define contracts", "Abstract classes share partial behavior", "Utility classes group stateless helpers"],
                "PaymentProcessor can be an interface; BaseReportJob can be abstract.",
                role_tags=["software engineer", "backend developer"],
                skill_tags=["java", "oop"],
            ),
            entry(
                "A Java API is suffering from frequent NullPointerExceptions in production. How would you systematically reduce them?",
                ["null", "Optional", "validation", "defensive coding", "contracts"],
                ["reliability", "API boundaries", "code quality"],
                ["Validate inputs at boundaries", "Use stronger contracts and object construction rules", "Use Optional carefully for absent return values"],
                "Require non-null DTO fields and validate them before service logic runs.",
                role_tags=["backend developer", "software engineer"],
                skill_tags=["java", "backend"],
            ),
        ],
        "advanced": [
            entry(
                "How does Java memory management work at a high level, and what kinds of issues can still happen even with garbage collection?",
                ["heap", "stack", "garbage collection", "memory leak", "references"],
                ["runtime memory", "gc behavior", "performance tuning"],
                ["GC reclaims unreachable objects", "Leaking references can still retain memory", "Pause times and allocation pressure still matter"],
                "Caching objects without eviction can cause practical leaks even with GC.",
                role_tags=["backend developer", "software engineer"],
                skill_tags=["java", "backend"],
            ),
            entry(
                "Compare synchronized blocks, locks, and concurrent collections in Java. How do you choose between them?",
                ["synchronized", "Lock", "concurrent", "thread-safe", "contention"],
                ["concurrency control", "thread safety", "performance tradeoffs"],
                ["Each option has different flexibility and overhead", "Concurrent collections reduce manual locking in common cases", "Choice depends on contention and complexity"],
                "ConcurrentHashMap often beats manual synchronized access for shared caches.",
                role_tags=["backend developer", "software engineer"],
                skill_tags=["java", "backend"],
            ),
            entry(
                "If a Spring-based Java service is experiencing thread pool exhaustion, what root causes would you investigate first?",
                ["thread pool", "blocking", "timeouts", "queue", "throughput"],
                ["production debugging", "resource saturation", "resilience"],
                ["Check blocking downstream calls", "Inspect timeouts and queue sizes", "Look for mismatched concurrency and CPU capacity"],
                "A slow DB client with missing timeouts can exhaust request threads.",
                role_tags=["backend developer"],
                skill_tags=["java", "spring", "backend"],
            ),
        ],
    },
    "javascript": {
        "beginner": [
            entry(
                "What is the difference between var, let, and const in JavaScript, and why does it matter in real code?",
                ["var", "let", "const", "scope", "hoisting"],
                ["variable declarations", "scope", "predictability"],
                ["var is function-scoped", "let/const are block-scoped", "const improves intent for non-reassigned bindings"],
                "for (let i = 0; i < 3; i++) { ... }",
                role_tags=["frontend developer", "full stack developer"],
                skill_tags=["javascript"],
            ),
            entry(
                "How would you explain the event loop to someone who is new to JavaScript?",
                ["event loop", "call stack", "callback queue", "async", "non-blocking"],
                ["runtime model", "asynchrony", "execution order"],
                ["JavaScript runs on a single call stack", "Async callbacks wait in queues", "The event loop schedules work back onto the stack"],
                "setTimeout(() => console.log('done'), 0)",
                role_tags=["frontend developer", "full stack developer"],
                skill_tags=["javascript"],
            ),
            entry(
                "What is the practical difference between == and === in JavaScript, and what team convention would you recommend?",
                ["==", "===", "coercion", "strict equality", "comparison"],
                ["type coercion", "bugs", "coding standards"],
                ["== performs coercion", "=== compares without coercion", "Strict equality is safer by default"],
                "0 == false is true, but 0 === false is false.",
                role_tags=["frontend developer", "software engineer"],
                skill_tags=["javascript"],
            ),
        ],
        "intermediate": [
            entry(
                "Compare callbacks, promises, and async/await. How would you decide which style to use in a production codebase?",
                ["callback", "promise", "async/await", "error handling", "readability"],
                ["asynchronous control flow", "maintainability", "composition"],
                ["Promises improve composition", "async/await improves readability", "Consistency matters more than novelty"],
                "const users = await api.fetchUsers()",
                role_tags=["frontend developer", "full stack developer", "backend developer"],
                skill_tags=["javascript", "api design"],
            ),
            entry(
                "A web page feels janky during user interactions. Which JavaScript-level performance problems would you inspect first?",
                ["rendering", "reflow", "debounce", "expensive loop", "main thread"],
                ["performance profiling", "ui responsiveness", "optimization"],
                ["Inspect long tasks on the main thread", "Reduce unnecessary DOM work", "Debounce or batch heavy events"],
                "Profile scroll handlers and repeated setState or DOM writes.",
                role_tags=["frontend developer"],
                skill_tags=["javascript", "react"],
            ),
            entry(
                "What are closures in JavaScript, and where do they help beyond interview examples?",
                ["closure", "scope", "state", "function", "lexical"],
                ["lexical scoping", "encapsulation", "higher-order functions"],
                ["Closures retain access to outer variables", "They help build factories and private state", "They are common in callbacks and hooks"],
                "function makeCounter(){ let count = 0; return () => ++count; }",
                role_tags=["frontend developer", "full stack developer"],
                skill_tags=["javascript"],
            ),
        ],
        "advanced": [
            entry(
                "How would you debug a memory leak in a long-lived JavaScript application such as a dashboard or SPA?",
                ["memory leak", "heap snapshot", "listeners", "timers", "retained objects"],
                ["browser debugging", "resource lifecycle", "cleanup"],
                ["Use browser profiling tools", "Check detached DOM nodes, listeners, and timers", "Trace retained references back to ownership issues"],
                "A removed modal that still has event listeners can stay in memory.",
                role_tags=["frontend developer", "full stack developer"],
                skill_tags=["javascript", "react"],
            ),
            entry(
                "What tradeoffs do you consider when splitting JavaScript bundles for a complex frontend application?",
                ["bundle splitting", "lazy loading", "cache", "initial load", "network"],
                ["performance strategy", "delivery optimization", "user experience"],
                ["Smaller initial bundles can improve first load", "Over-splitting can increase request overhead", "Split by route or feature boundaries"],
                "Load the admin dashboard bundle only for admin routes.",
                role_tags=["frontend developer"],
                skill_tags=["javascript", "react"],
            ),
            entry(
                "How do prototypes work in JavaScript, and when does understanding the prototype chain actually matter in production?",
                ["prototype", "inheritance", "__proto__", "lookup", "method sharing"],
                ["object model", "inheritance", "runtime lookup"],
                ["Objects delegate property lookup through prototypes", "Methods can be shared efficiently", "It matters when debugging inheritance and framework behavior"],
                "Array methods come from Array.prototype.",
                role_tags=["frontend developer", "software engineer"],
                skill_tags=["javascript"],
            ),
        ],
    },
    "sql": {
        "beginner": [
            entry(
                "What is the difference between WHERE and HAVING in SQL, and when would you use each?",
                ["WHERE", "HAVING", "filter", "GROUP BY", "aggregate"],
                ["query filtering", "aggregation", "execution order"],
                ["WHERE filters rows before grouping", "HAVING filters grouped results", "They solve different parts of the query"],
                "SELECT dept, COUNT(*) FROM employees GROUP BY dept HAVING COUNT(*) > 5;",
                role_tags=["data scientist", "backend developer", "data analyst"],
                skill_tags=["sql", "dbms"],
            ),
            entry(
                "Explain the difference between INNER JOIN, LEFT JOIN, and FULL OUTER JOIN using a simple example.",
                ["JOIN", "INNER", "LEFT", "FULL", "matching rows"],
                ["table relationships", "null handling", "result sets"],
                ["INNER returns matches only", "LEFT keeps left-side rows", "FULL includes unmatched rows from both sides"],
                "Use LEFT JOIN when you want all customers even if they have no orders.",
                role_tags=["data scientist", "backend developer", "data analyst"],
                skill_tags=["sql", "dbms"],
            ),
            entry(
                "Why do we use indexes in SQL databases, and what tradeoff do they introduce?",
                ["index", "lookup", "performance", "write overhead", "scan"],
                ["database optimization", "read/write tradeoffs", "query planning"],
                ["Indexes speed up reads", "They add storage and write cost", "Not every column should be indexed"],
                "An index on email speeds user lookup but makes inserts slightly more expensive.",
                role_tags=["backend developer", "data analyst", "data scientist"],
                skill_tags=["sql", "dbms"],
            ),
        ],
        "intermediate": [
            entry(
                "How would you reason about a slow SQL query before jumping straight to hardware upgrades?",
                ["execution plan", "index", "join order", "filtering", "cardinality"],
                ["query tuning", "root cause analysis", "database performance"],
                ["Inspect the execution plan", "Check indexes and selectivity", "Reduce scanned rows before blaming infrastructure"],
                "Use EXPLAIN to verify whether the query is doing a full table scan.",
                role_tags=["backend developer", "data scientist", "data analyst"],
                skill_tags=["sql", "dbms", "backend"],
            ),
            entry(
                "What are window functions in SQL, and when are they better than GROUP BY?",
                ["window function", "OVER", "partition", "rank", "running total"],
                ["analytical queries", "row context", "aggregation"],
                ["Window functions keep row-level detail", "They support ranking and running totals", "GROUP BY collapses rows"],
                "SELECT employee, salary, RANK() OVER (PARTITION BY dept ORDER BY salary DESC) FROM payroll;",
                role_tags=["data scientist", "data analyst", "backend developer"],
                skill_tags=["sql"],
            ),
            entry(
                "In a transactional system, how do you balance normalization with practical query performance?",
                ["normalization", "denormalization", "redundancy", "consistency", "performance"],
                ["schema design", "tradeoffs", "transactional systems"],
                ["Normalization reduces redundancy", "Denormalization can speed read-heavy paths", "You choose based on access patterns and consistency requirements"],
                "Keep orders normalized but precompute a reporting table for analytics.",
                role_tags=["backend developer", "database engineer"],
                skill_tags=["sql", "dbms", "backend"],
            ),
        ],
        "advanced": [
            entry(
                "Explain transaction isolation levels and the kinds of anomalies they are designed to prevent.",
                ["isolation", "dirty read", "non-repeatable read", "phantom read", "transaction"],
                ["concurrency control", "database consistency", "ACID"],
                ["Isolation levels trade performance for consistency", "Different anomalies are prevented at different levels", "Teams should pick the weakest safe level"],
                "Read committed prevents dirty reads but not all repeatability issues.",
                role_tags=["backend developer", "database engineer"],
                skill_tags=["sql", "dbms", "backend"],
            ),
            entry(
                "How would you design indexes for a table that serves both write-heavy APIs and read-heavy dashboards?",
                ["composite index", "covering index", "write-heavy", "read-heavy", "selectivity"],
                ["index strategy", "workload balancing", "database performance"],
                ["Start from critical queries", "Prefer selective and composite indexes aligned to filters", "Avoid over-indexing writes"],
                "One composite index on (status, created_at) may outperform several single-column indexes.",
                role_tags=["backend developer", "database engineer"],
                skill_tags=["sql", "dbms", "backend"],
            ),
            entry(
                "A report query is correct but too slow on production-sized data. What optimization levers would you evaluate in order?",
                ["partitioning", "materialized view", "pre-aggregation", "execution plan", "statistics"],
                ["performance engineering", "analytics at scale", "database architecture"],
                ["Confirm the bottleneck with plans and stats", "Consider indexing and query rewrites first", "Use partitioning or pre-aggregation when workload justifies it"],
                "Materialize daily aggregates instead of recalculating them from raw events for every request.",
                role_tags=["backend developer", "data engineer", "data scientist"],
                skill_tags=["sql", "dbms", "backend"],
            ),
        ],
    },
    "dsa": {
        "beginner": [
            entry(
                "What is Big O notation, and why is it useful even before you write optimized code?",
                ["Big O", "complexity", "time", "space", "growth"],
                ["algorithm analysis", "scalability", "tradeoffs"],
                ["Big O describes growth with input size", "It helps compare approaches early", "It guides design decisions before optimization"],
                "Linear search is O(n); binary search is O(log n) on sorted data.",
                role_tags=["software engineer", "backend developer", "data scientist"],
                skill_tags=["dsa"],
            ),
            entry(
                "When would you choose a hash table over an array or linked list?",
                ["hash table", "lookup", "array", "linked list", "tradeoff"],
                ["data structure choice", "lookup complexity", "memory tradeoffs"],
                ["Hash tables are great for fast average lookups", "Arrays are better for indexed order", "Choice depends on access pattern and constraints"],
                "Use a hash map to count frequencies in O(1) average lookup time.",
                role_tags=["software engineer", "backend developer"],
                skill_tags=["dsa"],
            ),
            entry(
                "Explain how a stack differs from a queue and give a real application for each.",
                ["stack", "queue", "LIFO", "FIFO", "operations"],
                ["core data structures", "access patterns", "use cases"],
                ["Stacks are LIFO", "Queues are FIFO", "Each maps naturally to different workflows"],
                "Undo history uses a stack; job scheduling often uses a queue.",
                role_tags=["software engineer", "backend developer"],
                skill_tags=["dsa"],
            ),
        ],
        "intermediate": [
            entry(
                "How does binary search work, and what are the most common implementation mistakes engineers make?",
                ["binary search", "sorted", "mid", "bounds", "loop condition"],
                ["search algorithms", "invariants", "edge cases"],
                ["Binary search halves the search space", "It requires a sorted condition or monotonic predicate", "Boundary handling is the usual bug source"],
                "Use while left <= right and update mid carefully to avoid infinite loops.",
                role_tags=["software engineer", "backend developer"],
                skill_tags=["dsa"],
            ),
            entry(
                "Compare BFS and DFS. How would you decide which traversal fits a problem better?",
                ["BFS", "DFS", "queue", "stack", "graph"],
                ["graph traversal", "search strategy", "problem modeling"],
                ["BFS explores level by level", "DFS goes deep first", "Choice depends on shortest path, memory, and search goals"],
                "BFS is natural for shortest unweighted path; DFS is useful for exhaustive exploration.",
                role_tags=["software engineer", "backend developer"],
                skill_tags=["dsa"],
            ),
            entry(
                "If you need to keep track of the top K largest elements in a stream, which data structure would you use and why?",
                ["top K", "heap", "priority queue", "stream", "min-heap"],
                ["streaming algorithms", "heap usage", "efficiency"],
                ["A min-heap of size K is efficient", "It keeps only the most valuable K items", "It avoids sorting the full stream repeatedly"],
                "Push each value into a min-heap and pop when size exceeds K.",
                role_tags=["software engineer", "data scientist", "backend developer"],
                skill_tags=["dsa"],
            ),
        ],
        "advanced": [
            entry(
                "How do you recognize when a dynamic programming approach is appropriate instead of a greedy or brute-force one?",
                ["dynamic programming", "overlapping subproblems", "optimal substructure", "memoization", "state"],
                ["problem decomposition", "optimization strategy", "algorithm design"],
                ["Look for repeated subproblems", "Define state and recurrence", "Compare against greedy assumptions before committing"],
                "Climbing stairs and edit distance are classic DP patterns.",
                role_tags=["software engineer"],
                skill_tags=["dsa"],
            ),
            entry(
                "Discuss the tradeoffs between adjacency lists and adjacency matrices in graph implementations.",
                ["adjacency list", "adjacency matrix", "sparse", "dense", "space"],
                ["graph representation", "space-time tradeoffs", "algorithm fit"],
                ["Lists are space-efficient for sparse graphs", "Matrices give O(1) edge checks", "Density and algorithm needs determine the choice"],
                "A dense network matrix may be fine; a sparse social graph usually prefers lists.",
                role_tags=["software engineer", "backend developer"],
                skill_tags=["dsa"],
            ),
            entry(
                "Imagine a recommendation service needs fast nearest-match retrieval at scale. How would you reason about data structures and algorithm choices?",
                ["retrieval", "index", "latency", "approximate", "scalability"],
                ["systems thinking", "algorithm selection", "tradeoffs"],
                ["Clarify exact vs approximate needs", "Use indexing structures appropriate to the data", "Balance latency, memory, and update cost"],
                "At scale, approximate nearest-neighbor techniques may outperform exact brute-force search.",
                role_tags=["software engineer", "data scientist"],
                skill_tags=["dsa", "backend"],
            ),
        ],
    },
    "oop": {
        "beginner": [
            entry(
                "Why is encapsulation more than just making fields private?",
                ["encapsulation", "private", "invariants", "API", "class"],
                ["object boundaries", "data hiding", "design intent"],
                ["Encapsulation protects invariants", "It exposes behavior instead of raw state", "It improves maintainability"],
                "A BankAccount should expose deposit() instead of letting callers mutate balance directly.",
                role_tags=["software engineer", "backend developer"],
                skill_tags=["oop", "java", "python"],
            ),
            entry(
                "Can inheritance make code worse? Give an example where composition would be a better fit.",
                ["inheritance", "composition", "reuse", "tight coupling", "flexibility"],
                ["design tradeoffs", "reuse strategy", "maintainability"],
                ["Inheritance can over-couple classes", "Composition favors flexible behavior assembly", "Choose the simplest relationship that matches reality"],
                "A NotificationService can compose an EmailSender instead of inheriting from it.",
                role_tags=["software engineer", "backend developer"],
                skill_tags=["oop"],
            ),
            entry(
                "How would you explain polymorphism to a junior developer without using a textbook definition?",
                ["polymorphism", "interface", "implementation", "substitution", "behavior"],
                ["abstraction", "interfaces", "extensibility"],
                ["Same interface can support multiple implementations", "Callers depend on behavior contracts", "This reduces branching in client code"],
                "PaymentProcessor can have CardProcessor and UpiProcessor implementations.",
                role_tags=["software engineer", "backend developer"],
                skill_tags=["oop"],
            ),
        ],
        "intermediate": [
            entry(
                "What makes an object-oriented design easy to extend without editing too many existing classes?",
                ["extensible", "interface", "dependency inversion", "single responsibility", "open closed"],
                ["solid principles", "maintainability", "abstraction"],
                ["Clear responsibilities reduce ripple effects", "Interfaces and composition isolate change", "Extension should avoid modifying stable code paths"],
                "Add a new ShippingCalculator implementation without changing checkout orchestration.",
                role_tags=["software engineer", "backend developer"],
                skill_tags=["oop"],
            ),
            entry(
                "How would you refactor a class that has grown into a 'god object'?",
                ["god object", "refactor", "responsibility", "extract", "cohesion"],
                ["code smells", "separation of concerns", "refactoring strategy"],
                ["Split responsibilities around cohesive behaviors", "Preserve behavior with tests while extracting", "Rebuild clearer boundaries and dependencies"],
                "Separate validation, persistence, and notification logic from an oversized OrderManager.",
                role_tags=["software engineer", "backend developer"],
                skill_tags=["oop", "backend"],
            ),
            entry(
                "How do design patterns help, and when do they become harmful ceremony?",
                ["design pattern", "factory", "strategy", "abstraction", "overengineering"],
                ["pattern literacy", "tradeoffs", "pragmatism"],
                ["Patterns capture reusable solutions", "They should reduce complexity, not add it", "Use them when the problem shape genuinely matches"],
                "Strategy is useful when behavior changes by context; it is not needed for one fixed implementation.",
                role_tags=["software engineer", "backend developer"],
                skill_tags=["oop"],
            ),
        ],
        "advanced": [
            entry(
                "Describe the Dependency Inversion Principle in practical engineering terms rather than memorized theory.",
                ["dependency inversion", "abstraction", "coupling", "interface", "injection"],
                ["architecture", "testability", "maintainability"],
                ["High-level code should depend on abstractions", "This reduces direct coupling", "It improves testing and changeability"],
                "CheckoutService depends on a PaymentGateway interface, not a StripeGateway class directly.",
                role_tags=["software engineer", "backend developer"],
                skill_tags=["oop", "backend"],
            ),
            entry(
                "How would you model a domain where business rules change often without creating a fragile inheritance tree?",
                ["rules engine", "composition", "strategy", "configuration", "domain model"],
                ["domain modeling", "change management", "flexible design"],
                ["Favor composable behaviors", "Encapsulate volatile rules separately", "Keep the core model stable and explicit"],
                "Discount rules can be strategies configured per campaign instead of subclassing Order for every offer.",
                role_tags=["software engineer", "backend developer"],
                skill_tags=["oop", "backend"],
            ),
            entry(
                "What signals tell you a codebase is object-oriented in syntax but procedural in design?",
                ["anemic model", "god service", "data bag", "behavior", "encapsulation"],
                ["design critique", "architecture smell", "object design"],
                ["Objects with no behavior are a clue", "All logic in service layers suggests weak modeling", "Encapsulation is missing if state is widely manipulated"],
                "DTO-heavy systems are not automatically domain-driven or truly object-oriented.",
                role_tags=["software engineer", "backend developer"],
                skill_tags=["oop"],
            ),
        ],
    },
    "dbms": {
        "beginner": [
            entry(
                "What is normalization in DBMS, and why isn't 'more normalized' always automatically better?",
                ["normalization", "redundancy", "anomaly", "schema", "table"],
                ["database design", "consistency", "tradeoffs"],
                ["Normalization reduces redundancy and anomalies", "Highly normalized schemas can complicate reads", "Design depends on workload"],
                "A reporting system may deliberately denormalize some fields for faster reads.",
                role_tags=["backend developer", "data analyst", "software engineer"],
                skill_tags=["dbms", "sql"],
            ),
            entry(
                "Explain primary keys and foreign keys with a real-world example from an e-commerce system.",
                ["primary key", "foreign key", "relationship", "integrity", "reference"],
                ["relational modeling", "integrity constraints", "schema design"],
                ["Primary keys uniquely identify rows", "Foreign keys relate tables", "They preserve referential integrity"],
                "orders.user_id references users.id",
                role_tags=["backend developer", "data analyst"],
                skill_tags=["dbms", "sql"],
            ),
            entry(
                "What is the difference between logical data independence and physical data independence?",
                ["logical", "physical", "data independence", "schema", "storage"],
                ["database abstraction", "architecture", "DBMS benefits"],
                ["Logical independence separates app logic from logical schema changes", "Physical independence hides storage changes", "DBMS layers reduce coupling"],
                "Changing indexes should not break application queries.",
                role_tags=["software engineer", "backend developer"],
                skill_tags=["dbms"],
            ),
        ],
        "intermediate": [
            entry(
                "How do ACID properties show up in an online payment workflow?",
                ["ACID", "atomicity", "consistency", "isolation", "durability"],
                ["transactions", "correctness", "reliability"],
                ["Atomicity avoids partial updates", "Consistency maintains valid state", "Durability preserves committed data"],
                "Debit and ledger updates should commit together or both roll back.",
                role_tags=["backend developer", "software engineer"],
                skill_tags=["dbms", "backend"],
            ),
            entry(
                "What kinds of database anomalies can happen without proper schema design or transaction discipline?",
                ["insert anomaly", "update anomaly", "delete anomaly", "consistency", "redundancy"],
                ["schema quality", "data correctness", "relational design"],
                ["Poor design can duplicate facts inconsistently", "Normalization and transactions reduce anomalies", "Explain with a concrete example"],
                "Updating one copy of a supplier address but missing another causes inconsistency.",
                role_tags=["backend developer", "data analyst"],
                skill_tags=["dbms", "sql"],
            ),
            entry(
                "How would you evaluate whether a system should stay relational or move part of its workload to a NoSQL store?",
                ["relational", "NoSQL", "consistency", "schema", "scalability"],
                ["data architecture", "tradeoffs", "workload fit"],
                ["Base the decision on access patterns and consistency needs", "Not all scale problems require NoSQL", "Polyglot persistence can be valid"],
                "Session caching may fit Redis while financial records stay relational.",
                role_tags=["backend developer", "software engineer"],
                skill_tags=["dbms", "backend", "mongodb"],
            ),
        ],
        "advanced": [
            entry(
                "How do replication and sharding solve different classes of database scaling problems?",
                ["replication", "sharding", "read scale", "write scale", "partition"],
                ["distributed databases", "scaling strategy", "availability"],
                ["Replication improves availability and read capacity", "Sharding distributes data across nodes", "Each adds operational complexity"],
                "Read replicas help analytics, while sharding may be needed for very large write workloads.",
                role_tags=["backend developer", "software engineer"],
                skill_tags=["dbms", "backend"],
            ),
            entry(
                "What tradeoffs do you consider before enabling eventual consistency in a distributed data system?",
                ["eventual consistency", "staleness", "latency", "availability", "conflict"],
                ["distributed systems", "consistency models", "product tradeoffs"],
                ["Eventual consistency can improve availability and latency", "It introduces temporary staleness", "Choice depends on user and domain expectations"],
                "A social feed can tolerate stale counts; account balances usually cannot.",
                role_tags=["backend developer", "software engineer"],
                skill_tags=["dbms", "backend"],
            ),
            entry(
                "Suppose a product team wants auditability, rollback, and analytical history from the same data model. How would you reason about database design options?",
                ["audit trail", "history", "event sourcing", "snapshot", "ledger"],
                ["data modeling", "compliance", "system design"],
                ["Clarify the exact audit and rollback needs", "Append-only or event-style models may help", "Operational simplicity still matters"],
                "You may combine a transactional table with an append-only audit log for traceability.",
                role_tags=["backend developer", "software engineer"],
                skill_tags=["dbms", "backend"],
            ),
        ],
    },
    "operating systems": {
        "beginner": [
            entry(
                "What is the difference between a process and a thread, and why should backend engineers care?",
                ["process", "thread", "memory", "execution", "concurrency"],
                ["runtime units", "resource sharing", "system behavior"],
                ["Processes isolate memory", "Threads share process memory", "This affects performance, safety, and concurrency choices"],
                "A web server may use multiple threads within one process to serve requests.",
                role_tags=["backend developer", "software engineer"],
                skill_tags=["operating systems", "linux"],
            ),
            entry(
                "How does CPU scheduling impact the responsiveness of a system that runs many tasks at once?",
                ["scheduling", "CPU", "fairness", "latency", "throughput"],
                ["resource allocation", "responsiveness", "os basics"],
                ["Schedulers decide which task runs next", "Different goals balance latency and throughput", "Too much context switching also has cost"],
                "Interactive apps need fast response while batch jobs may prefer throughput.",
                role_tags=["software engineer", "backend developer"],
                skill_tags=["operating systems"],
            ),
            entry(
                "What is virtual memory, and why is it useful even when a machine already has RAM?",
                ["virtual memory", "paging", "address space", "RAM", "isolation"],
                ["memory abstraction", "protection", "resource management"],
                ["Virtual memory gives each process an address space", "It enables isolation and flexible allocation", "Pages can move between RAM and disk-backed storage"],
                "Two processes can both think they are using address 0x1000 safely.",
                role_tags=["software engineer", "backend developer"],
                skill_tags=["operating systems"],
            ),
        ],
        "intermediate": [
            entry(
                "A service keeps slowing down because of excessive context switching. What conditions usually cause that?",
                ["context switching", "threads", "contention", "CPU", "blocking"],
                ["performance diagnosis", "scheduler behavior", "resource contention"],
                ["Too many runnable threads can cause churn", "Lock contention and blocking patterns contribute", "The fix depends on workload shape"],
                "A thread pool far larger than available cores can create overhead without more throughput.",
                role_tags=["backend developer", "software engineer"],
                skill_tags=["operating systems", "backend"],
            ),
            entry(
                "How would you explain deadlock using a production-style example rather than a classroom example?",
                ["deadlock", "lock", "resource", "wait", "cycle"],
                ["concurrency hazards", "resource ordering", "system reliability"],
                ["Deadlock happens when actors wait on each other cyclically", "Multiple locks/resources can create it", "Ordering and timeouts reduce risk"],
                "Service A holds a DB lock and waits on a cache lock while another flow does the reverse.",
                role_tags=["backend developer", "software engineer"],
                skill_tags=["operating systems", "backend"],
            ),
            entry(
                "Why do engineers care about file descriptors, and what production failures can happen when they run out?",
                ["file descriptor", "socket", "limit", "resource leak", "open files"],
                ["os resources", "production debugging", "network services"],
                ["Descriptors represent open files and sockets", "Leaks can block new connections", "Monitoring limits is important in long-running services"],
                "A leaking socket connection can eventually trigger 'too many open files'.",
                role_tags=["backend developer", "devops engineer"],
                skill_tags=["operating systems", "linux", "backend"],
            ),
        ],
        "advanced": [
            entry(
                "How does the kernel-user space boundary affect performance and security decisions in system design?",
                ["kernel", "user space", "syscall", "isolation", "performance"],
                ["system architecture", "security", "overhead"],
                ["Kernel mode has privileged access", "Crossing the boundary through syscalls has cost", "Isolation improves safety"],
                "Too many tiny syscalls can hurt throughput; batching I/O may help.",
                role_tags=["backend developer", "software engineer"],
                skill_tags=["operating systems", "backend"],
            ),
            entry(
                "If a Linux server shows high load average but low CPU usage, what hypotheses would you investigate?",
                ["load average", "CPU", "I/O wait", "blocked tasks", "disk"],
                ["system diagnosis", "performance analysis", "linux internals"],
                ["Load average includes runnable and uninterruptible tasks", "Disk or network wait can inflate load", "CPU percentage alone can mislead"],
                "Processes stuck in disk I/O can raise load without saturating CPU.",
                role_tags=["devops engineer", "backend developer"],
                skill_tags=["operating systems", "linux"],
            ),
            entry(
                "How would you reason about tuning a system for throughput versus tail latency at the OS level?",
                ["throughput", "latency", "tail latency", "queueing", "resource contention"],
                ["systems optimization", "performance tradeoffs", "capacity planning"],
                ["Optimizing for average throughput can hurt worst-case latency", "Queue sizes and concurrency limits matter", "Measure under realistic load before tuning"],
                "Large queues can keep throughput high while making p99 latency unacceptable.",
                role_tags=["backend developer", "software engineer"],
                skill_tags=["operating systems", "backend"],
            ),
        ],
    },
    "computer networks": {
        "beginner": [
            entry(
                "What happens at a high level when you type a URL into your browser and hit Enter?",
                ["DNS", "TCP", "HTTP", "request", "response"],
                ["web request lifecycle", "networking basics", "client-server flow"],
                ["The browser resolves DNS", "It establishes a connection and sends HTTP", "The server responds with content"],
                "DNS lookup -> TCP/TLS handshake -> HTTP request -> response rendering",
                role_tags=["frontend developer", "backend developer", "software engineer"],
                skill_tags=["computer networks", "api design"],
            ),
            entry(
                "What is the difference between TCP and UDP, and when is each one a better fit?",
                ["TCP", "UDP", "reliable", "connectionless", "latency"],
                ["transport protocols", "tradeoffs", "network behavior"],
                ["TCP provides reliable ordered delivery", "UDP is lighter and faster but less reliable", "Choice depends on app needs"],
                "Video streaming may tolerate UDP-like behavior; payments need TCP reliability.",
                role_tags=["backend developer", "software engineer"],
                skill_tags=["computer networks"],
            ),
            entry(
                "Why do we need DNS, and what common failures happen when DNS is unhealthy?",
                ["DNS", "name resolution", "domain", "cache", "lookup"],
                ["service discovery", "internet basics", "failure modes"],
                ["DNS maps names to addresses", "Caching affects freshness and availability", "Resolution failures can look like total outages"],
                "A working server can appear down if clients cannot resolve its hostname.",
                role_tags=["backend developer", "devops engineer"],
                skill_tags=["computer networks"],
            ),
        ],
        "intermediate": [
            entry(
                "How does HTTPS actually make web traffic safer than plain HTTP?",
                ["HTTPS", "TLS", "certificate", "encryption", "integrity"],
                ["transport security", "authentication", "privacy"],
                ["TLS encrypts traffic", "Certificates help authenticate the server", "It also protects message integrity"],
                "Without HTTPS, a shared Wi-Fi attacker may inspect or tamper with traffic.",
                role_tags=["backend developer", "frontend developer", "software engineer"],
                skill_tags=["computer networks", "api design"],
            ),
            entry(
                "A service is intermittently timing out, but only for some users in some regions. How would you investigate from a networking angle?",
                ["latency", "routing", "timeout", "region", "packet loss"],
                ["network troubleshooting", "distributed systems", "observability"],
                ["Compare regional latency and packet loss", "Check DNS, CDN, and routing paths", "Differentiate app errors from network path issues"],
                "Traceroute, edge logs, and regional metrics can reveal route-specific failures.",
                role_tags=["backend developer", "devops engineer"],
                skill_tags=["computer networks", "backend"],
            ),
            entry(
                "What are common causes of connection resets and broken pipes in client-server systems?",
                ["connection reset", "broken pipe", "timeout", "socket", "keep-alive"],
                ["network failures", "socket lifecycle", "service resilience"],
                ["One side can close the socket unexpectedly", "Timeouts and idle connection handling often cause this", "Retry strategy depends on request safety"],
                "A proxy closing idle keep-alive connections can trigger resets on reused sockets.",
                role_tags=["backend developer"],
                skill_tags=["computer networks", "backend"],
            ),
        ],
        "advanced": [
            entry(
                "How would you reason about load balancing strategies for APIs with mixed traffic patterns?",
                ["load balancing", "round robin", "least connections", "sticky sessions", "health checks"],
                ["traffic management", "high availability", "system design"],
                ["Strategy depends on statefulness and traffic variability", "Health checks and failover are essential", "Stickiness can solve some problems while creating others"],
                "Least-connections may help uneven request durations more than plain round robin.",
                role_tags=["backend developer", "devops engineer"],
                skill_tags=["computer networks", "backend"],
            ),
            entry(
                "What networking considerations matter when designing for retries, idempotency, and downstream failures?",
                ["retry", "idempotency", "timeout", "backoff", "duplicate request"],
                ["resilience", "distributed systems", "API reliability"],
                ["Retries can amplify failures if done blindly", "Idempotency protects against duplicate effects", "Timeouts and backoff need thoughtful tuning"],
                "A payment API should expose an idempotency key before clients retry on network errors.",
                role_tags=["backend developer", "software engineer"],
                skill_tags=["computer networks", "backend", "api design"],
            ),
            entry(
                "If you were debugging inconsistent API latency, how would you separate application issues from pure network issues?",
                ["latency", "observability", "tracing", "hop", "network"],
                ["performance isolation", "distributed tracing", "diagnosis"],
                ["Use end-to-end traces and hop metrics", "Compare server processing time to total request time", "Correlate with regional or path-based signals"],
                "If server time is low but total latency is high, the network path or edge layer may be the culprit.",
                role_tags=["backend developer", "devops engineer"],
                skill_tags=["computer networks", "backend"],
            ),
        ],
    },
    "react": {
        "beginner": [
            entry(
                "Why is React built around components, and how does that help large frontend teams?",
                ["component", "reuse", "props", "UI", "composition"],
                ["component architecture", "reuse", "maintainability"],
                ["Components break UI into manageable pieces", "They encourage reuse and consistency", "They help teams reason about isolated concerns"],
                "A product card component can be reused across listing, search, and recommendations.",
                role_tags=["frontend developer", "full stack developer"],
                skill_tags=["react", "javascript"],
            ),
            entry(
                "What is the difference between props and state in React?",
                ["props", "state", "data flow", "component", "update"],
                ["react fundamentals", "component ownership", "rendering"],
                ["Props come from parents", "State is owned and managed by the component", "This supports predictable data flow"],
                "A parent passes product data as props while a child keeps local modal-open state.",
                role_tags=["frontend developer"],
                skill_tags=["react"],
            ),
            entry(
                "Why do React lists need keys, and what kinds of bugs happen when keys are unstable?",
                ["key", "list", "reconciliation", "identity", "render"],
                ["UI diffing", "component identity", "bugs"],
                ["Keys help React track identity across renders", "Stable keys prevent mismatched state", "Array indexes are risky when order changes"],
                "Using index keys in reorderable lists can move input state to the wrong row.",
                role_tags=["frontend developer"],
                skill_tags=["react"],
            ),
        ],
        "intermediate": [
            entry(
                "How would you decide whether state should live in a local component, a parent component, or a shared store?",
                ["state", "lifting state", "global store", "ownership", "scope"],
                ["state management", "data ownership", "architecture"],
                ["Keep state as local as possible", "Lift it when multiple children need it", "Use shared stores only for broadly shared concerns"],
                "A form field stays local; authenticated user data often belongs in app-level state.",
                role_tags=["frontend developer", "full stack developer"],
                skill_tags=["react"],
            ),
            entry(
                "A React page re-renders too often and feels slow. What would you inspect before adding memoization everywhere?",
                ["re-render", "state updates", "profiling", "props", "memoization"],
                ["performance debugging", "render behavior", "premature optimization"],
                ["Profile first", "Find unnecessary state churn and parent rerenders", "Memoization should be targeted, not automatic"],
                "React DevTools Profiler can reveal a hot component tree caused by a noisy parent state update.",
                role_tags=["frontend developer"],
                skill_tags=["react"],
            ),
            entry(
                "What problems do hooks solve in React, and what are the most common hook misuse patterns?",
                ["hooks", "useEffect", "useState", "custom hook", "dependency array"],
                ["component logic reuse", "side effects", "stateful logic"],
                ["Hooks let function components manage state and effects", "Custom hooks reuse logic cleanly", "Misuse often comes from effect dependencies or stale closures"],
                "A useFetch custom hook can centralize loading, data, and error logic.",
                role_tags=["frontend developer"],
                skill_tags=["react"],
            ),
        ],
        "advanced": [
            entry(
                "How would you debug a React effect that causes an infinite render loop in a production feature?",
                ["useEffect", "dependency", "loop", "state update", "stale closure"],
                ["side-effect management", "debugging", "react lifecycle"],
                ["Find which effect updates state repeatedly", "Inspect dependency arrays and unstable references", "Separate derived state from effects where possible"],
                "An effect depending on an inline object can retrigger forever.",
                role_tags=["frontend developer"],
                skill_tags=["react"],
            ),
            entry(
                "What tradeoffs do you consider when choosing between client-side fetching, server rendering, and incremental loading strategies?",
                ["SSR", "CSR", "hydration", "loading", "SEO"],
                ["rendering strategy", "performance", "user experience"],
                ["Choose based on SEO, latency, caching, and interactivity needs", "Server rendering improves first content in some cases", "Client fetching can simplify dynamic workflows"],
                "A marketing page may prefer SSR while an internal dashboard may stay client-rendered.",
                role_tags=["frontend developer", "full stack developer"],
                skill_tags=["react", "api design"],
            ),
            entry(
                "How would you structure a large React codebase so feature delivery stays fast without turning components into a tangled mess?",
                ["feature folder", "design system", "state boundaries", "hooks", "ownership"],
                ["frontend architecture", "scalability", "team productivity"],
                ["Organize by feature or domain, not just file type", "Separate shared UI primitives from feature logic", "Keep ownership boundaries explicit"],
                "A design system can hold generic button/input components while checkout-specific hooks stay under checkout.",
                role_tags=["frontend developer"],
                skill_tags=["react"],
            ),
        ],
    },
    "backend": {
        "beginner": [
            entry(
                "What responsibilities usually belong in a backend service, and which ones do not?",
                ["backend", "business logic", "validation", "database", "API"],
                ["service boundaries", "responsibilities", "architecture"],
                ["Backends typically handle business rules, persistence, and integrations", "Some validation belongs at multiple layers", "UI-specific concerns should stay out"],
                "A backend should validate order totals; it should not decide button colors or layout.",
                role_tags=["backend developer", "full stack developer"],
                skill_tags=["backend", "api design"],
            ),
            entry(
                "Why do backend systems need validation at the API boundary even if the frontend already validates input?",
                ["validation", "boundary", "security", "integrity", "trust"],
                ["defensive programming", "API design", "correctness"],
                ["Clients cannot be fully trusted", "Different clients may call the same API", "Backend validation protects correctness and security"],
                "Mobile, web, and third-party clients may all call the same endpoint.",
                role_tags=["backend developer"],
                skill_tags=["backend", "api design"],
            ),
            entry(
                "What is caching, and what kinds of bugs can appear if you use it without a clear strategy?",
                ["cache", "latency", "stale data", "invalidation", "performance"],
                ["performance optimization", "consistency", "tradeoffs"],
                ["Caching reduces repeated expensive work", "Staleness and invalidation are the hard parts", "You need clear ownership of freshness guarantees"],
                "A product price cache that is not invalidated can show old pricing after an admin update.",
                role_tags=["backend developer", "software engineer"],
                skill_tags=["backend", "redis"],
            ),
        ],
        "intermediate": [
            entry(
                "How would you structure error handling in a backend API so that logs are useful and clients get consistent responses?",
                ["error handling", "logging", "status code", "exception", "observability"],
                ["API contracts", "debuggability", "operational clarity"],
                ["Use consistent response shapes", "Log with context and correlation IDs", "Avoid leaking internals to clients"],
                "Return a stable error code to clients while keeping stack traces in server logs.",
                role_tags=["backend developer"],
                skill_tags=["backend", "api design"],
            ),
            entry(
                "A backend feature works correctly in tests but fails under concurrent traffic. What categories of issues do you investigate first?",
                ["race condition", "locking", "idempotency", "transaction", "shared state"],
                ["concurrency bugs", "correctness under load", "state safety"],
                ["Look for shared mutable state", "Check transaction boundaries and duplicate request handling", "Load can expose order-dependent failures"],
                "Two workers updating the same inventory row can oversell stock without safe coordination.",
                role_tags=["backend developer", "software engineer"],
                skill_tags=["backend", "dbms"],
            ),
            entry(
                "How do queues and background jobs help backend systems, and what new failure modes do they introduce?",
                ["queue", "worker", "retry", "async", "eventual consistency"],
                ["system decoupling", "reliability", "workflow design"],
                ["Queues decouple slow work from request paths", "They improve responsiveness and resilience", "Retries, ordering, and duplicate processing need design"],
                "Send emails asynchronously so checkout is fast, but make the job idempotent.",
                role_tags=["backend developer"],
                skill_tags=["backend", "api design"],
            ),
        ],
        "advanced": [
            entry(
                "What tradeoffs do you consider when moving from a monolith to microservices, and when is that move a mistake?",
                ["monolith", "microservices", "complexity", "deployment", "ownership"],
                ["architecture tradeoffs", "organizational fit", "scalability"],
                ["Microservices add autonomy but also complexity", "Operational maturity matters", "Premature decomposition can slow teams down"],
                "A small team may move faster with a modular monolith than a fleet of services.",
                role_tags=["backend developer", "software engineer"],
                skill_tags=["backend"],
            ),
            entry(
                "How would you reason about idempotency for write APIs that may be retried by clients or gateways?",
                ["idempotency", "retry", "duplicate", "write API", "safety"],
                ["API reliability", "distributed systems", "correctness"],
                ["Retried requests must avoid duplicate side effects", "Unique request identities can help", "The storage model must support safe deduplication"],
                "Creating orders with an idempotency key can prevent duplicate charges.",
                role_tags=["backend developer"],
                skill_tags=["backend", "api design"],
            ),
            entry(
                "A service is scaling but operational incidents keep rising. What architecture or engineering practices would you strengthen first?",
                ["observability", "rate limiting", "timeouts", "resilience", "runbook"],
                ["reliability engineering", "operational maturity", "system health"],
                ["Strengthen visibility before guessing", "Add safe failure controls like timeouts and circuit breaking", "Invest in incident learning and ownership"],
                "Better tracing and dependency timeouts often reduce incident duration faster than rewriting code blindly.",
                role_tags=["backend developer", "software engineer", "devops engineer"],
                skill_tags=["backend", "api design"],
            ),
        ],
    },
    "api design": {
        "beginner": [
            entry(
                "What makes an API easy for another engineer to use without constant clarification?",
                ["API", "clear contract", "naming", "documentation", "consistency"],
                ["developer experience", "interface design", "clarity"],
                ["Clear naming and predictable behavior matter", "Errors and examples should be understandable", "Consistency reduces support load"],
                "GET /users/{id} is clearer than vague action-heavy endpoints.",
                role_tags=["backend developer", "full stack developer", "frontend developer"],
                skill_tags=["api design", "backend"],
            ),
            entry(
                "How would you choose appropriate HTTP methods and status codes for a CRUD-style API?",
                ["GET", "POST", "PUT", "PATCH", "DELETE", "status code"],
                ["HTTP semantics", "REST basics", "API correctness"],
                ["Methods should match intent", "Status codes should communicate outcome clearly", "Consistency matters more than cleverness"],
                "Use POST for creation and 201 Created when a resource is successfully created.",
                role_tags=["backend developer", "full stack developer"],
                skill_tags=["api design"],
            ),
            entry(
                "Why is pagination important in APIs, and what issues appear if you ignore it?",
                ["pagination", "limit", "offset", "cursor", "response size"],
                ["scalability", "API usability", "performance"],
                ["Pagination protects latency and payload size", "It helps clients consume large datasets safely", "Naive pagination strategies can still cause correctness issues"],
                "Cursor pagination often behaves better than offsets on changing data.",
                role_tags=["backend developer", "frontend developer"],
                skill_tags=["api design", "backend"],
            ),
        ],
        "intermediate": [
            entry(
                "How do you design API error responses so clients can recover intelligently instead of guessing?",
                ["error response", "code", "message", "retryable", "validation"],
                ["API ergonomics", "client resilience", "contracts"],
                ["Responses should separate machine-readable and human-readable parts", "Clients should know whether to retry, fix input, or stop", "Errors should be stable over time"],
                '{"code":"validation_failed","message":"email is required","details":{"field":"email"}}',
                role_tags=["backend developer", "frontend developer"],
                skill_tags=["api design", "backend"],
            ),
            entry(
                "When is versioning an API necessary, and what are the costs of versioning too eagerly?",
                ["versioning", "backward compatibility", "contract", "migration", "breaking change"],
                ["API lifecycle", "change management", "compatibility"],
                ["Version only when compatibility cannot be preserved", "Too many versions create maintenance burden", "Prefer additive change when possible"],
                "Adding a nullable field may avoid a version bump; removing a required field usually does not.",
                role_tags=["backend developer", "software engineer"],
                skill_tags=["api design"],
            ),
            entry(
                "How would you handle rate limiting for a public API without making the platform frustrating for legitimate users?",
                ["rate limiting", "quota", "burst", "429", "fairness"],
                ["platform protection", "consumer experience", "abuse prevention"],
                ["Protect shared capacity fairly", "Communicate limits clearly", "Different consumers may need different policies"],
                "Return 429 with retry guidance and expose remaining quota headers when appropriate.",
                role_tags=["backend developer"],
                skill_tags=["api design", "backend"],
            ),
        ],
        "advanced": [
            entry(
                "What tradeoffs do you consider when choosing between REST, GraphQL, and asynchronous event-driven interfaces for a product surface?",
                ["REST", "GraphQL", "events", "contract", "consumer needs"],
                ["interface strategy", "system design", "tradeoffs"],
                ["Match the interface style to product and consumer needs", "Operational complexity differs across models", "No single style wins every case"],
                "GraphQL can reduce over-fetching for flexible clients, while events suit decoupled workflows.",
                role_tags=["backend developer", "software engineer", "full stack developer"],
                skill_tags=["api design", "backend"],
            ),
            entry(
                "How would you design an API for eventually consistent workflows so clients still have a good user experience?",
                ["eventual consistency", "polling", "webhook", "status", "async workflow"],
                ["distributed workflows", "UX communication", "consistency expectations"],
                ["Expose workflow state clearly", "Provide polling or callback options", "Document timing and failure behavior"],
                '{"job_id":"123","status":"processing"}',
                role_tags=["backend developer", "software engineer"],
                skill_tags=["api design", "backend"],
            ),
            entry(
                "A partner integration keeps breaking because of ambiguous contracts. How would you redesign the interface and rollout process?",
                ["contract", "schema", "sandbox", "compatibility", "documentation"],
                ["integration design", "external API governance", "operational rollout"],
                ["Tighten schema clarity and examples", "Introduce better validation and testing environments", "Roll out changes with explicit compatibility guarantees"],
                "A sandbox plus contract tests can catch breaking changes before production traffic does.",
                role_tags=["backend developer", "software engineer"],
                skill_tags=["api design", "backend"],
            ),
        ],
    },
    "behavioral": {
        "beginner": [
            entry(
                "Tell me about a time you had to learn a new concept quickly to finish a task. How did you approach it?",
                ["learn", "approach", "resource", "result", "reflection"],
                ["structured communication", "learning mindset", "ownership"],
                ["Give a concrete situation", "Explain the actions and result", "Reflect on what you learned"],
                "I broke the concept into small parts, built a quick prototype, and asked for feedback early.",
                role_tags=["software engineer", "frontend developer", "backend developer", "data scientist"],
                skill_tags=["behavioral"],
            ),
            entry(
                "Describe a time you received constructive feedback. What did you do with it?",
                ["feedback", "response", "improvement", "ownership", "growth"],
                ["coachability", "self-awareness", "professional maturity"],
                ["Show openness to feedback", "Explain the change you made", "Highlight measurable improvement"],
                "I turned recurring review comments into a checklist and my rework dropped significantly.",
                role_tags=["software engineer", "frontend developer", "backend developer", "data scientist"],
                skill_tags=["behavioral"],
            ),
            entry(
                "How do you communicate progress when you are blocked but still trying to make forward progress?",
                ["blocker", "communication", "progress", "help", "clarity"],
                ["teamwork", "communication", "ownership"],
                ["Communicate early and clearly", "Share what you tried", "Ask for targeted help while continuing useful work"],
                "I post the blocker, failed attempts, and the smallest decision I need from a teammate.",
                role_tags=["software engineer", "frontend developer", "backend developer"],
                skill_tags=["behavioral"],
            ),
        ],
        "intermediate": [
            entry(
                "Tell me about a disagreement with a teammate on a technical decision. How did you handle it?",
                ["disagreement", "technical decision", "tradeoff", "alignment", "outcome"],
                ["collaboration", "conflict resolution", "decision making"],
                ["Show respect and curiosity", "Use data or experiments to evaluate options", "Focus on the team outcome over ego"],
                "We compared rollout risk and maintenance cost, then ran a small spike before deciding.",
                role_tags=["software engineer", "backend developer", "frontend developer"],
                skill_tags=["behavioral"],
            ),
            entry(
                "Describe a project where requirements were unclear. How did you create enough structure to move forward?",
                ["ambiguity", "requirements", "stakeholders", "clarify", "execution"],
                ["ambiguity handling", "ownership", "product thinking"],
                ["Clarify goals and constraints", "Make assumptions visible", "Use checkpoints to validate direction early"],
                "I wrote a short proposal with assumptions and got it reviewed before building the core flow.",
                role_tags=["software engineer", "product manager", "backend developer", "frontend developer"],
                skill_tags=["behavioral"],
            ),
            entry(
                "When have you deliberately traded speed for quality, and how did you justify that decision?",
                ["quality", "speed", "risk", "tradeoff", "decision"],
                ["engineering judgment", "risk management", "communication"],
                ["Explain the context and risk", "Show how you aligned stakeholders", "Demonstrate balanced judgment rather than perfectionism"],
                "We delayed a launch by one day because data loss risk was still unacceptably high.",
                role_tags=["software engineer", "backend developer", "frontend developer"],
                skill_tags=["behavioral"],
            ),
        ],
        "advanced": [
            entry(
                "Tell me about a time you had to influence a decision without direct authority. What worked and what did not?",
                ["influence", "stakeholder", "alignment", "authority", "decision"],
                ["leadership", "communication", "organizational awareness"],
                ["Frame the problem around shared goals", "Use evidence and empathy", "Reflect honestly on what changed minds"],
                "I translated the risk into customer impact, not just engineering frustration.",
                role_tags=["software engineer", "lead/manager", "backend developer", "frontend developer"],
                skill_tags=["behavioral"],
            ),
            entry(
                "Describe a difficult production incident or project miss. How did you respond in the moment and what changed afterward?",
                ["incident", "ownership", "retrospective", "communication", "improvement"],
                ["accountability", "incident response", "learning culture"],
                ["Separate immediate stabilization from long-term fixes", "Communicate clearly under pressure", "Show what process or design changed afterward"],
                "We stabilized traffic first, then added better alerting and rollout safeguards in the retrospective.",
                role_tags=["backend developer", "software engineer", "devops engineer"],
                skill_tags=["behavioral"],
            ),
            entry(
                "How do you mentor less experienced teammates without becoming a bottleneck yourself?",
                ["mentor", "enablement", "scaling", "documentation", "feedback"],
                ["leadership", "team growth", "systems thinking"],
                ["Prefer teaching patterns over one-off fixes", "Create reusable guidance", "Balance availability with autonomy"],
                "I pair once, document the pattern, and then review the next attempt rather than solving it repeatedly.",
                role_tags=["software engineer", "lead/manager", "backend developer", "frontend developer"],
                skill_tags=["behavioral"],
            ),
        ],
    },
}


TOPIC_METADATA: Dict[str, Dict[str, List[str]]] = {
    "python": {"prerequisites": [], "core_topics": ["basics", "functions", "generators"]},
    "java": {"prerequisites": ["oop"], "core_topics": ["JVM", "collections", "concurrency"]},
    "javascript": {"prerequisites": [], "core_topics": ["runtime", "async", "closures"]},
    "sql": {"prerequisites": ["dbms"], "core_topics": ["queries", "joins", "transactions"]},
    "dsa": {"prerequisites": [], "core_topics": ["complexity", "trees", "graphs"]},
    "oop": {"prerequisites": [], "core_topics": ["abstraction", "composition", "design"]},
    "dbms": {"prerequisites": [], "core_topics": ["schema", "transactions", "scaling"]},
    "operating systems": {"prerequisites": [], "core_topics": ["processes", "memory", "scheduling"]},
    "computer networks": {"prerequisites": [], "core_topics": ["tcp/ip", "dns", "tls"]},
    "react": {"prerequisites": ["javascript"], "core_topics": ["components", "state", "effects"]},
    "backend": {"prerequisites": ["api design", "dbms"], "core_topics": ["services", "caching", "queues"]},
    "api design": {"prerequisites": ["computer networks"], "core_topics": ["http", "contracts", "versioning"]},
    "behavioral": {"prerequisites": [], "core_topics": ["communication", "ownership", "leadership"]},
}


SKILL_ALIASES: Dict[str, List[str]] = {
    "python": ["python", "backend"],
    "java": ["java", "oop", "backend"],
    "javascript": ["javascript", "react", "api design"],
    "sql": ["sql", "dbms"],
    "mongodb": ["dbms", "backend"],
    "postgresql": ["sql", "dbms"],
    "mysql": ["sql", "dbms"],
    "redis": ["backend", "dbms"],
    "react": ["react", "javascript", "behavioral"],
    "django": ["python", "backend", "api design"],
    "flask": ["python", "backend", "api design"],
    "spring": ["java", "backend", "api design"],
    "angular": ["javascript", "api design"],
    "tensorflow": ["python", "dsa"],
    "aws": ["backend", "computer networks", "operating systems"],
    "docker": ["backend", "operating systems"],
    "kubernetes": ["backend", "operating systems", "computer networks"],
    "git": ["behavioral", "backend"],
    "linux": ["operating systems", "backend"],
    "jenkins": ["backend", "operating systems"],
    "c++": ["dsa", "operating systems"],
    "c#": ["oop", "backend"],
    "go": ["backend", "computer networks"],
    "rust": ["operating systems", "backend"],
    "php": ["backend", "api design"],
    "frontend developer": ["react", "javascript", "api design", "behavioral", "computer networks"],
    "software engineer": ["python", "dsa", "oop", "sql", "behavioral"],
    "backend developer": ["backend", "sql", "dbms", "api design", "computer networks", "operating systems"],
    "full stack developer": ["react", "javascript", "backend", "api design", "sql", "behavioral"],
    "data scientist": ["python", "sql", "dsa", "dbms", "behavioral"],
    "data analyst": ["sql", "dbms", "behavioral"],
    "machine learning engineer": ["python", "dsa", "sql", "backend", "behavioral"],
    "devops engineer": ["operating systems", "computer networks", "backend", "behavioral"],
    "cloud architect": ["backend", "computer networks", "operating systems", "api design"],
    "product manager": ["behavioral", "api design"],
    "qa engineer": ["behavioral", "backend", "api design"],
    "lead/manager": ["behavioral", "backend", "oop"],
}
